"""Visual specimens for the MVP presentation system, not presentation content."""
from pathlib import Path
import re, base64
P=Path(__file__).resolve().parent
R=P.parents[2]
font=re.search(r'@font-face\{[^}]+\}',(R/'deliverables/plan/proposal-deck-presented.html').read_text(encoding='utf-8')).group()
css=(P/'design/presentation.css').read_text(encoding='utf-8')
logo='data:image/svg+xml;base64,'+base64.b64encode((P/'assets/foothold-lockup-compact-dark.svg').read_bytes()).decode()
page='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FOOTHOLD MVP · 디자인 기준 견본</title><style>__FONT____CSS__
*{box-sizing:border-box}body{margin:0;background:#12161d;font-family:var(--p-font)}.frame{height:calc(100vw * .5625);position:relative;overflow:hidden;margin-bottom:24px}.p-slide{transform:scale(var(--s));transform-origin:top left;padding:64px}p,h1,h2,h3{margin:0}.row{display:flex;justify-content:space-between;align-items:center}.tag{font-size:20px;color:var(--p-muted)}.space{margin-top:96px}.line{border-top:1px solid var(--p-rule);margin:32px 0}.spec{display:grid;grid-template-columns:288px 1fr;align-items:baseline;margin:24px 0}.spec label{font-size:20px;color:var(--p-muted)}.bottom{position:absolute;bottom:64px;left:64px;right:64px}.swatches{display:flex;gap:32px;margin-top:48px}.swatch{width:256px}.swatch i{height:16px;display:block;background:var(--c);margin-bottom:16px}.swatch strong{font-size:20px;color:var(--ct,var(--c))}.swatch p{font-size:18px;line-height:1.5;margin-top:12px;color:var(--p-muted)}
</style><body>
<div class="frame"><section class="p-slide p-dark"><div class="row"><img src="__LOGO__" width="280" alt="FOOTHOLD"><span class="tag">MVP 발표 디자인 기준 · 시각 견본</span></div><div class="space"><p class="p-label p-emphasis">주제 구간 · 40px</p><h1 class="p-chapter" style="margin-top:24px">어디에서<br>첫걸음을 시작했을까?</h1></div><div class="bottom"><div class="line"></div><p class="p-subtitle">Find the next foothold.</p><p class="p-caption" style="margin-top:16px">불확실한 지형에서도, 다음 걸음을 이어갑니다.</p><p class="p-source" style="margin-top:32px">고정: 로고·아이콘·기울기·폰트 느낌·슬로건　 /　 변형: 배치·이미지·정보 위계·전환</p></div></section></div>
<div class="frame"><section class="p-slide"><div class="row"><p class="p-label p-emphasis">내용의 위계</p><span class="tag">서체·크기·간격 견본 · 실제 발표 슬라이드 아님</span></div><div style="margin-top:64px"><div class="spec"><label>슬라이드 제목 · 26</label><h2 class="p-title">실패에서 다음 실험을 찾다</h2></div><div class="line"></div><div class="spec"><label>서브주제 · 22</label><h3 class="p-subtitle">왜 gap부터 시작했을까?</h3></div><div class="spec"><label>본문 · 20</label><p class="p-body">관측 처리를 보완하고, 틈을 학습에 추가했습니다.</p></div><div class="spec"><label>강조 · 같은 크기</label><p class="p-body">먼저 <span class="p-emphasis">무엇이 실패했는지</span> 확인했습니다.</p></div><div class="spec"><label>그림 라벨 · 18</label><p class="p-label">관측 입력　 /　 actor　 /　 관절 위치 목표</p></div><div class="spec"><label>조건·캡션 · 16</label><p class="p-caption">비교 조건은 그림 가까이에 표시합니다.</p></div><div class="spec"><label>출처 · 16</label><p class="p-source">출처와 링크는 하단에 고정하고, 중요한 조건은 본문에 남깁니다.</p></div></div><p class="p-source bottom">각 화면을 같은 배치로 만드는 대신, 역할이 같은 정보의 표현을 통일합니다.</p></section></div>
<div class="frame"><section class="p-slide"><div class="row"><p class="p-label p-emphasis">색과 움직임의 의미</p><span class="tag">브랜드를 참고한 MVP용 기준안</span></div><h2 class="p-title" style="margin-top:80px">같은 의미는 같은 표현으로</h2><div class="swatches"><div class="swatch" style="--c:var(--p-ink)"><i></i><strong>기본 정보</strong><p>제목·본문·비교 기준</p></div><div class="swatch" style="--c:var(--p-brand);--ct:var(--p-brand-text)"><i></i><strong>청록</strong><p>핵심 강조·현재 위치·채택</p></div><div class="swatch" style="--c:var(--p-note);--ct:var(--p-note-text)"><i></i><strong>앰버</strong><p>주의·미확인</p></div><div class="swatch" style="--c:var(--p-danger)"><i></i><strong>적색</strong><p>실패·금지</p></div></div><div class="line" style="margin-top:64px"></div><div class="spec"><label>설명 애니메이션</label><p class="p-body">한 번의 클릭에 한 가지 변화. 이전 상태와 연결.</p></div><div class="spec"><label>픽셀 Go2</label><p class="p-body">걷기·틈 넘기·경사 오르기. 발 디딤까지 실제 동작.</p></div><div class="spec"><label>영상과 연구 근거</label><p class="p-body">실제 실험과 생성 콘셉트 장면을 구분.</p></div><p class="p-source bottom">이 견본에는 수치 실험 결과나 완성된 픽셀 Go2 동작을 넣지 않았습니다.</p></section></div>
<script>function resize(){document.documentElement.style.setProperty('--s',innerWidth/1600)}resize();addEventListener('resize',resize)</script></body></html>'''
page=page.replace('__FONT__',font).replace('__CSS__',css).replace('__LOGO__',logo)
assert '\u2014' not in page
(P/'output/FOOTHOLD-MVP-design-system.html').write_text(page,encoding='utf-8')
print('디자인 기준 시각 견본 생성 완료')
